version: '3'
services:
  server:
    image: 'acsp-fl-server:latest'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:8080  # O servidor escutará em todas as interfaces
      - NUM_CLIENTS=3
      - NUM_ROUNDS=100
      - ALGORITHM=DEEV
      - POC=0
      - SOLUTION_NAME=ACSP-FL
      - DATASET=MNIST
      - MODEL=DNN
      - DECAY=0
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"  # Expõe a porta para permitir conexões externas
    networks:
      - fl_network

networks:
  fl_network:
    driver: bridge
    


